/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts_xir2_pbo;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Puspita
 */
public class form_daftar extends javax.swing.JFrame {

    /**
     * Creates new form form_dafter
     */
    public form_daftar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Alamat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        NoStruk = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        NoPolisi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Kembali = new com.toedter.calendar.JDateChooser();
        Pinjam = new com.toedter.calendar.JDateChooser();
        Hari = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Harga = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        Print = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Tanggal kembali :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 230, 100, 20);
        jPanel2.add(Nama);
        Nama.setBounds(140, 30, 140, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Alamat :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(70, 70, 60, 20);
        jPanel2.add(Alamat);
        Alamat.setBounds(140, 70, 140, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("No Struk :");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(70, 110, 60, 20);
        jPanel2.add(NoStruk);
        NoStruk.setBounds(140, 110, 140, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("No. Polisi :");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(70, 150, 60, 20);
        jPanel2.add(NoPolisi);
        NoPolisi.setBounds(140, 150, 140, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Lama Peminjaman :");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 270, 120, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Tanggal pinjam :");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 190, 100, 20);
        jPanel2.add(Kembali);
        Kembali.setBounds(140, 230, 160, 30);
        jPanel2.add(Pinjam);
        Pinjam.setBounds(140, 190, 160, 30);
        jPanel2.add(Hari);
        Hari.setBounds(140, 270, 140, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Harga :");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(70, 310, 50, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("hari");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(290, 280, 50, 20);
        jPanel2.add(Harga);
        Harga.setBounds(140, 310, 140, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Nama :");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(70, 30, 50, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(260, 80, 340, 360);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("CentSchbkCyrill BT", 1, 18)); // NOI18N
        jLabel6.setText("FORM PEMINJAMAN MOTOR");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 0, 290, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(260, 30, 340, 40);

        tabel.setBackground(new java.awt.Color(204, 255, 204));
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "Alamat", "NoStruk", "NoPolisi", "TanggalPinjam", "TanggalKembali", "LamaPinjam", "Hari"
            }
        ));
        jScrollPane2.setViewportView(tabel);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(620, 100, 620, 330);

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setLayout(null);

        Print.setText("Print");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        jPanel4.add(Print);
        Print.setBounds(480, 10, 80, 40);

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel4.add(Save);
        Save.setBounds(10, 10, 80, 40);

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel4.add(Delete);
        Delete.setBounds(140, 10, 80, 40);

        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel4.add(Clear);
        Clear.setBounds(260, 10, 80, 40);

        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        jPanel4.add(Refresh);
        Refresh.setBounds(370, 10, 80, 40);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(620, 30, 600, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tglPinjam = dateFormat.format(Pinjam.getDate());
        String tglKembali = dateFormat.format(Kembali.getDate());
        if("".equals(Nama.getText()) || "".equals(Alamat.getText()) || "".equals(NoStruk.getText()) ||
                "".equals(NoPolisi.getText()) || "".equals(Hari.getText()) || "".equals(Harga.getText())){
            JOptionPane.showMessageDialog(this, "Mohon untuk melengkapi data terlebih dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
           
        }
        String SQL = "INSERT INTO t_daftar (Nama,Alamat,NoStruk,NoPolisi,TanggalPinjam,TanggalKembali,Hari,Harga)"
                + "VALUES ('"+Nama.getText()+"','"+Alamat.getText()
                + "','"+NoStruk.getText()+"','"+NoPolisi.getText()+"',"
                + "'"+tglPinjam+"','"+tglKembali+"','"+Hari.getText()+"','"+Harga.getText()+"')";
        int status = KoneksiDB.execute(SQL);
        if (status == 1) {
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            selectData();
        } else {
            JOptionPane.showMessageDialog(this,"Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        int baris = tabel.getSelectedRow();
        if(baris != -1) {
            String Nama = tabel.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_daftar WHERE Nama='"+Nama+"'";
            int status = KoneksiDB.execute(SQL);
            
            if (status==1) {
                JOptionPane.showMessageDialog(this,"Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,"Data gagal dihapus","Gagal",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        Nama.setText("");
        Alamat.setText("");
        NoStruk.setText("");
        Pinjam.setDate(null);
        Kembali.setDate(null);
        NoPolisi.setText(""); 
        Harga.setText("");
        Hari.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_RefreshActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Penyewaan motor");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}       ");
        try {
            tabel.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);            
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_PrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_daftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alamat;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField Harga;
    private javax.swing.JTextField Hari;
    private com.toedter.calendar.JDateChooser Kembali;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField NoPolisi;
    private javax.swing.JTextField NoStruk;
    private com.toedter.calendar.JDateChooser Pinjam;
    private javax.swing.JButton Print;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton Save;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"Nama","Alamat","NoStruk","NoPolisi","TanggalPinjam","TanggalKembali"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM t_daftar";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()) {
                String Nama = rs.getString(1);
                String Alamat = rs.getString(2);
                String NoStruk = rs.getString(3);
                String NoPolisi = rs.getString(4);
                String TanggalPinjam = rs.getString(5);
                String TanggalKembali = rs.getString(6);
                String Hari = rs.getString(7);
                String Harga = rs.getString(8);
                String tabel[] = {Nama,Alamat,NoStruk,NoPolisi,TanggalPinjam,TanggalKembali,Hari,Harga};
                dtm.addRow(tabel);
            }
        } catch (SQLException ex) {
            Logger.getLogger(form_daftar.class.getName()).log(Level.SEVERE, null, ex);
        } tabel.setModel(dtm);
    }

}
